add: added wave task and changed the topic name to be ablo to receive…
tidewise/simulation-orogen-gazebo_usv pull request #8
Opened 2022-10-06 20:57 UTC by kapeps

… recursive ones

2022-10-07 14:29 UTC, jhonasiv commented on tasks/WaveSourceTask.cpp
> +    mWaveFrequencyPublisher->Publish(wave_per_msg);
I suppose the `per` is for period, does the message contain information about the wave period or frequency?

2022-10-10 16:31 UTC, afonsofonbraga requested changes

2022-10-10 16:31 UTC, afonsofonbraga commented on tasks/WaveSourceTask.hpp
> +        gazebo::transport::PublisherPtr mWaveAmplitudePublisher;
According to the latest coding standard all variables must be snake_case and private/protected should start with m_

2022-10-17 19:34 UTC, afonsofonbraga approved these changes

2022-10-18 14:06 UTC, afonsofonbraga approved these changes

2022-10-20 17:04 UTC, kapeps commented on tasks/DirectForceApplicationTask.cpp
> +    auto topic_name = mModelName + "/" + _link_name.get() + "/gazebo_usv_force";
We are using it, as the mModelName is set at setGazeboModel

2022-10-20 17:14 UTC, kapeps commented on gazebo_usv.orogen
> +    exception_states 'NO_TOPIC_CONNECTION'
Some tasks dont use this exception_state, is it universal?

2022-10-21 18:59 UTC, jhonasiv approved these changes

2022-10-25 20:06 UTC, seixasxbr approved these changes

2022-10-25 20:08 UTC, afonsofonbraga approved these changes

2022-10-27 20:15 UTC, merged